spring:
  datasource:
    url: jdbc:h2:mem:test_mem
    driver-class-name: org.h2.Driver
    password: sa
    username: sa
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelogs/db.changelog-master.yaml
server:
    port: 9090